"""Fictional sample electronics catalog; prices and specifications are demo data."""
PRODUCTS = [
    dict(name='AeroBook Pro 14',brand='AERO',category='Laptops',price=8999900,compare_price=9999900,stock=18,image='laptop',description='Big ideas. Light footprint. A precision-built notebook for your everyday workflow.',specs={'Display':'14-inch 2.8K OLED','Processor':'8-core performance processor','Memory':'16 GB','Storage':'512 GB SSD','Battery':'Up to 12 hours','Weight':'1.35 kg'}),
    dict(name='Nova One Smartphone',brand='NOVA',category='Phones',price=3499900,compare_price=3999900,stock=32,image='phone',description='Capture more of your world with a fluid display and a versatile camera system.',specs={'Display':'6.5-inch AMOLED · 120 Hz','Camera':'50 MP dual camera','Memory':'8 GB','Storage':'256 GB','Battery':'5,000 mAh','Connectivity':'5G · Wi-Fi 6'}),
    dict(name='Sonic Air Max',brand='SONIC',category='Audio',price=899900,compare_price=1199900,stock=40,image='headphones',description='Find your focus. Wireless over-ear headphones with active noise cancellation.',specs={'Type':'Wireless over-ear','Noise control':'Active noise cancellation','Battery':'Up to 40 hours','Connectivity':'Bluetooth 5.3','Charging':'USB-C','Weight':'250 g'}),
    dict(name='Pulse Watch S2',brand='PULSE',category='Wearables',price=649900,compare_price=799900,stock=27,image='watch',description='A smarter companion for your day, from morning routines to evening movement.',specs={'Display':'1.8-inch AMOLED','Battery':'Up to 7 days','Resistance':'IP68','Connectivity':'Bluetooth 5.3','Features':'Activity tracking · notifications','Case':'Aluminium'}),
    dict(name='AeroView 27 Monitor',brand='AERO',category='Gaming',price=2299900,compare_price=2699900,stock=15,image='monitor',description='A sharper view and smoother play. Bring your workspace and games to life.',specs={'Display':'27-inch IPS','Resolution':'2560 × 1440','Refresh rate':'165 Hz','Response':'1 ms rated','Ports':'HDMI · DisplayPort','Stand':'Height adjustable'}),
    dict(name='Sonic Buds Mini',brand='SONIC',category='Audio',price=299900,compare_price=399900,stock=60,image='earbuds',description='Small enough to go everywhere. Clear calls and an easy all-day soundtrack.',specs={'Type':'True wireless earbuds','Battery':'Up to 24 hours with case','Connectivity':'Bluetooth 5.3','Resistance':'IPX4','Charging':'USB-C','Microphones':'Dual microphones'}),
    dict(name='Nova Pad 11',brand='NOVA',category='Tablets',price=2499900,compare_price=2999900,stock=24,image='tablet',description='Space to create, watch and explore. A versatile tablet with an immersive display.',specs={'Display':'11-inch 2K LCD','Memory':'6 GB','Storage':'128 GB','Battery':'8,000 mAh','Connectivity':'Wi-Fi 6','Weight':'490 g'}),
    dict(name='Flux Mechanical Keyboard',brand='FLUX',category='Accessories',price=499900,compare_price=649900,stock=45,image='keyboard',description='Make every keystroke count. A compact mechanical keyboard with a satisfying feel.',specs={'Layout':'75% compact','Switches':'Tactile mechanical','Lighting':'RGB backlight','Connection':'USB-C wired','Compatibility':'Windows · macOS','Keycaps':'Double-shot PBT'}),
    dict(name='Flux Precision Mouse',brand='FLUX',category='Gaming',price=249900,compare_price=329900,stock=55,image='mouse',description='Precision without the weight. A responsive mouse built for work and play.',specs={'Sensor':'Optical · 12,000 DPI','Buttons':'6 programmable','Connection':'2.4 GHz wireless','Battery':'Up to 60 hours','Charging':'USB-C','Weight':'68 g'}),
    dict(name='Volt Charge 65',brand='VOLT',category='Accessories',price=199900,compare_price=249900,stock=70,image='charger',description='One compact charger for your daily devices, with efficient GaN technology.',specs={'Power':'65 W maximum','Technology':'GaN','Ports':'2 × USB-C · 1 × USB-A','Input':'100–240 V','Protocol':'USB Power Delivery','Cable':'Sold separately'}),
    dict(name='Sonic Room Speaker',brand='SONIC',category='Audio',price=549900,compare_price=699900,stock=28,image='speaker',description='Room-filling sound in a compact speaker. Take your favorite playlists along.',specs={'Output':'20 W','Battery':'Up to 15 hours','Connectivity':'Bluetooth 5.3','Resistance':'IPX5','Charging':'USB-C','Features':'Stereo pairing'}),
    dict(name='AeroBook Everyday 15',brand='AERO',category='Laptops',price=5499900,compare_price=5999900,stock=22,image='laptop',description='A dependable everyday laptop with room for projects, classes and entertainment.',specs={'Display':'15.6-inch Full HD IPS','Processor':'6-core efficiency processor','Memory':'16 GB','Storage':'512 GB SSD','Battery':'Up to 9 hours','Weight':'1.7 kg'}),
]
